---
- name: Webservers Configurations
  hosts: all
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        upgrade: yes

- hosts: all
  tasks:
  - name: Install Apache2    
    apt:
      name: apache2
      state: present

  - name: install php
    apt:
      - php
      - libapache2-mod-php
    state: present

  - name: Set timezone to Africa/Lagos
    timezone:
      name: Africa/Lagos

  - name: Create root directory
    file:
      path: /var/www/html/
      state: directory
      owner: www-data
      group: www-data
      mode: 0777


  - name: Display hostname
    synchronize:
      src: /home/ibechuks/patrickaziken/
      dest: /var/www/html/

  handlers:
  - name: restart_apache
    systemd:
      name: apache2
      state: restarted
