---
- hosts: all
  become: true
  tasks:
  - name: install updates
    apt:
      update_cache: yes
      upgrade: dist
  
  - name: install apache
    apt:
      name: apache2
      state: latest

  - name: copy default php file
    copy:
      src: index.php
      dest: /var/www/html/index.php
      owner: root
      group: root
      mode: 0644


  - name: delete index.html
    file:
      path: /var/www/html/index.html
      state: absent


