---
- name: Webservers Configurations
  hosts: all
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        upgrade: yes

  roles:
    - apache2
    - load_app
    - set_timezone  
