---
- name: Deploy App
  apt:
    name:
      - php
      - libapache2-mod-php
    state: present

- name: Create root ducument directory
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: Copy App assets to Servers
  synchronize:
    src: /home/ibechuks/Patrick\ Aziken/
    dest: /var/www/html/ 
    delete: yes

